### ISSUE TITLE
refactor shutdown sequence to use plugin.stop

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-graphite#4]
Change shutdown sequence to be triggered by plugin.stop instead of ShutdownSignal exception.
Also remove any calls to: shutdown, finished, finished?, running? or terminating?
This depends on https://github.com/elastic/logstash/pull/3895

**Comment by untergeek** [comment]
Because this plugin very simply calls the tcp input plugin as a super class, this plugin _depends_ on https://github.com/logstash-plugins/logstash-input-tcp/pull/8 being completed.

Once finished, this will work out of the box.

**Comment by untergeek** [comment]
Pretty sure this is covered now.
